### ISSUE TITLE
Properly package up before testing

### ISSUE THREAD

**Issue by bettiolo** [dashy-io/dashy-server-api#10]
Use `npm purge` and `npm shrinkwrap`

**Comment by framp** [comment]
Shrinkwrap generated and I don't see anything to purge (and `depcheck` says we don't have unused dependencies)

Looks OK to me, reopen if you have other plans.

**Comment by bettiolo** [comment]
The scope of this issue was to add npm purge && npm shrinkwrap before running tests to ensure that the expected environment will be deployed

**Comment by framp** [comment]
`npm purge` is not a valid command and I'm not sure why we need this.

`npm shrinkwrap` is meant to be run on the developer machine in order to generate a `npm-shrinkwrap.json` which locks dependencies (similar to a `Gemfile.lock`). 
If there is `npm-shrinkwrap.json` file at `npm install` time it will be used instead of `package.json` to install dependencies.

The `npm-shrinkwrap.json` has been added in 83fd108

**Comment by bettiolo** [comment]
Yeah, the command I was referring is `npm prune`, sorry for the confusion: https://docs.npmjs.com/cli/prune

The idea is that you prune AND shrinkwap before running tests so that when you push the changes, CI server will have the same exact packages as you had when you executed the tests.

**Comment by framp** [comment]
We don't need prune either, as we don't have extraneous packages on the CI server and calling `npm prune` won't delete any package.

What do you want to do with `npm prune`?
Doing what you suggest doesn't make sense as `npm shrinkwrap` needs you to have some package installed (otherwise it doesn't have any package to lock) which is not the case on the CI server.

Also, calling `npm shrinkwrap` is not something to be done on the server, as the result needs to be added to the repository to guarantee in future installs that the same set of packages is being used.

**Comment by bettiolo** [comment]
The `npm prune` command is to ensure that you don't have extraneous packages on your local machine while running the tests, as the tests may pass and would then fail on CI.

`npm prune` and `npm shrinkwrap` needs to be executed on the local development machine to "crystallize" the state of the dependencies before pushing it and shipping it to CI.

**Comment by framp** [comment]
Exactly, on the **local development machine**.
If we add them in `npm test` they will be run also on the CI.

That's why I suggest we use `npm shrinkwrap` as a separate command whenever we install or update a new dependency and just commit  the result in the VCS.

**Comment by bettiolo** [comment]
@framp is there any problem if CI executes `npm test` after we have pushed the latest changes? I think it will be redundant but it should have no impact. The advantage is that we ensure the tests are executed with exactly the same dependency set.

**Comment by framp** [comment]
Not really, just a useless write!

So, it's basically a way to protect developers from installing random dependencies in node_modules?

Makes sense, added `npm prune && npm shrinkwrap` to `npm test` and codeship is happy ;)

**Comment by bettiolo** [comment]
OK, thanks!
